# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliveVouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('validupto', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('model', models.TextField()),
                ('sex', models.TextField()),
                ('appmode', models.TextField()),
                ('accesstoken', models.TextField()),
                ('appversion', models.TextField()),
                ('handsettype', models.TextField()),
                ('osversion', models.TextField()),
                ('profileimage', models.TextField()),
                ('deviceid', models.TextField()),
                ('mobileno', models.TextField()),
                ('socialid', models.TextField()),
                ('username', models.TextField()),
                ('manufacture', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField()),
                ('tokenexpire', models.TextField()),
                ('logintype', models.TextField()),
                ('advid', models.TextField()),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='alivevouchers',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b20.Users'),
        ),
    ]
