# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliveVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.TextField(unique=True)),
                ('coupondate', models.DateField(null=True)),
                ('expirydate', models.DateField(null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BMSVouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.TextField(unique=True)),
                ('coupondate', models.DateField(null=True)),
                ('expirydate', models.DateField(null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True)),
                ('appmode', models.CharField(default='AND', max_length=10)),
                ('accesstoken', models.TextField(default='EAACVuZCS6jj4BAKaCynep1cdIdzjAIP9p4vRPxJQ5ZBxRvuvscUqiapCOmEMDuWjH5fce5hOs5NIg2XCPu4iMM8bkvm3Pqn6OfIGdrggmTm3jObcWRSOwIGZCGZBkJZAkwVBVLBOhcOPG6xARjghVnf2Czt5MZBOaXJnyAy5Leh5OAL7qvKsInHiVX3LV5Jsv9ZCcVdED7DLrxvgNpIJXfQ')),
                ('appversion', models.CharField(max_length=10)),
                ('handsettype', models.CharField(max_length=10)),
                ('osversion', models.CharField(max_length=10)),
                ('profileimage', models.URLField()),
                ('deviceid', models.CharField(max_length=20)),
                ('mobileno', models.CharField(blank=True, max_length=12, null=True)),
                ('socialid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('manufacture', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(blank=True, max_length=12, null=True)),
                ('tokenexpire', models.CharField(max_length=55)),
                ('logintype', models.CharField(default='FB', max_length=20)),
                ('advid', models.CharField(max_length=40)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='bmsvouchers',
            name='serid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b20.User'),
        ),
        migrations.AddField(
            model_name='alivevoucher',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b20.User'),
        ),
    ]
