# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0002_auto_20161101_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accesstoken',
            field=models.TextField(default='EAACVuZCS6jj4BAKaCynep1cdIdzjAIP9p4vRPxJQ5ZBxRvuvscUqiapCOmEMDuWjH5fce5hOs5NIg2XCPu4iMM8bkvm3Pqn6OfIGdrggmTm3jObcWRSOwIGZCGZBkJZAkwVBVLBOhcOPG6xARjghVnf2Czt5MZBOaXJnyAy5Leh5OAL7qvKsInHiVX3LV5Jsv9ZCcVdED7DLrxvgNpIJXfQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='advid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='appmode',
            field=models.CharField(default='AND', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='appversion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='deviceid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='handsettype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='logintype',
            field=models.CharField(default='FB', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manufacture',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='osversion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileimage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='socialid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokenexpire',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
