# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0003_auto_20161101_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deviceid',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='socialid',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
