# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0005_auto_20161101_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deviceid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='socialid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokenexpire',
            field=models.CharField(max_length=55),
        ),
    ]
