# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0006_auto_20161102_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alivevoucher',
            old_name='code',
            new_name='couponcode',
        ),
        migrations.RemoveField(
            model_name='alivevoucher',
            name='validupto',
        ),
        migrations.AddField(
            model_name='alivevoucher',
            name='coupondate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alivevoucher',
            name='expirydate',
            field=models.DateField(null=True),
        ),
    ]
