# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0008_auto_20161103_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.TextField(unique=True)),
                ('coupondate', models.DateField(null=True)),
                ('expirydate', models.DateField(null=True)),
                ('used', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b20.User')),
            ],
        ),
    ]
