# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0009_bmsvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alivevoucher',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='bmsvoucher',
            name='expirydate',
        ),
        migrations.AlterField(
            model_name='bmsvoucher',
            name='coupondate',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
