# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0010_auto_20161213_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
