# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b20', '0011_user_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliveQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.TextField(unique=True)),
                ('ans', models.TextField()),
            ],
        ),
    ]
