# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('b20', '0013_auto_20170114_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsvoucher',
            name='coupondate',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
